### ISSUE TITLE
Train own Data

### ISSUE THREAD

**Issue by JoeHEZHAO** [TobyPDE/FRRN#15]
Hey, thanks for sharing the code. This is a fantastic idea to do semantic segmentation. 

May I ask: is there a way to utilize your code on other data, like my own data ? Is there an instruction for this purpose ?

Best
He Zhao

**Comment by TobyPDE** [comment]
Yes, it is possible. I will soon add some APIs in order to make training on new data easier. Before I do this, you can train on your own data using the newly added train_custom.py file. I added "TODO" instructions where you need to fill in some custom values. The most important thing is to convert your annotation to the correct format. Please see the corresponding remark in the file for further details.

**Comment by MyVanitar** [comment]
@TobyPDE 

Hi,
Have you updated the fine-tuning section? We also need a pre-trained model. 
Also May I ask you how can we fine-tune with different number of classes?

**Comment by TobyPDE** [comment]
You can fine-tune by replacing the last layer of the network. Initialize all weights to the pre-trained ones and randomly initialize the new last layer. Then train on your own data.

**Comment by Jorisfournel** [comment]
Hi,
The file you describe here is not to be found anymore. I would like to train your data on a medical segmentation issue, I have my own dataset and just need to understand what to do to train your network on my data. I'm struggeling with getting into your code and it's not easy since all I find about datas in your code is references to cs_folder. I'm not familiar with python on top of that, which doesn't help ... 

Thanks in advance for any help
