### ISSUE TITLE
Performance on Other datasets.

### ISSUE THREAD

**Issue by D-X-Y** [TobyPDE/FRRN#19]
Thanks for your greate work, have you ever test your algorithm on PASCAL VOC or COCO datasets?

**Comment by Tetsujinfr** [comment]
Following up on the above question from DXY, no comment on alternative datasets Toby? tks

**Comment by TobyPDE** [comment]
Hey, sorry for the late reply. I'm currently in the process of finishing the refactor of the code before the poster presentation at CVPR tomorrow. 

We haven't experimented substantially on other datasets due to time and resource constraints before the deadline. I no longer work in this area and don't have the capacity to run large scale evaluations. However, with the new code, which I will push tonight, I made it very simple to train and evaluate the architecture on new datasets. So, you should be able to train new models yourself easily.

**Comment by Tetsujinfr** [comment]
Thanks for coming back to us. Looking forward for your update tonight Toby. 
Sad you do not look at this field anymore but I can see from your cv that you got likely new interesting challenges to tackle down here in London. All the best in your new role.

**Comment by Tetsujinfr** [comment]
Hi Toby,

Any chance with the code update?

Hope all is good at CVPR. I guess you may update after the conf is over.
Pls drop a quick note if you have a chance.

Thanks
Tets

**Comment by TobyPDE** [comment]
Hey, 

I'm working on it right now. I currently write a Python alternative for the Chianti library so people can try the code without compiling a custom Python extension. Should be done soon. I'll post here once the update is pushed online.

**Comment by Tetsujinfr** [comment]
Excellent, thanks. Brilliant for Chianti given I could not compile properly
somehow.

Tets

**Comment by Tetsujinfr** [comment]
Hi, any chance with an update Toby? I was hoping to give it a try this week
but I guess you are busy . Would you expect an update sometime in August?
Your model looks great, so keen to test it.

Tets

**Comment by TobyPDE** [comment]
I just published the update. You can now run the code without the C++ library. However, installing the new version of Chianti will give you a significant performance boost.

**Comment by Tetsujinfr** [comment]
You are my hero, thanks so much Toby. I hope I can find the time to compile
it tonight et test.
Thanks again for your great work on this.

Tets

On 27 Jul 2017 8:01 pm, "Toby Pohlen" <notifications@github.com> wrote:

Closed #19 <https://github.com/TobyPDE/FRRN/issues/19>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/TobyPDE/FRRN/issues/19#event-1182347414>, or mute the
thread
